### PR TITLE
fix: incompatible CLI usage since v5

### PR DESCRIPTION
**Pull request by digglife**
CLI interface has been changed since v5, so we need to make the script work for both v4 and v5.

fixes: #243

### CODE REVIEW

**Comment by digglife** [comment]
@IceCodeNew could you please review the code?

**Comment by digglife** [comment]
@kslr @nicholascw @lucifer9 

Do you have the authorization to review and merge PR for this repo?  Not sure why @IceCodeNew didn't respond.

The script is one of the [recommended ways](https://www.v2fly.org/guide/install.html#linux-%E5%AE%89%E8%A3%85%E6%96%B9%E5%BC%8F) to install v2ray on Linux, yet this issue has been out there for a week without actions from maintainers.  Kind of abnormal because it's quite critical.

**Comment by dctxmei** [comment]
@digglife I sent a PR (digglife/fhs-install-v2ray#1) to your repository and it is working fine with me :)

**Comment by digglife** [comment]
> @digglife I sent a PR (digglife/fhs-install-v2ray#1) to your repository and it is working fine with me :)

I don't get it. What's the issue you tried to fix with that?

**Comment by dctxmei** [comment]
On Wed, Sep 14, 2022 at 10:01:37PM -0700, 朱聖黎 Zhu Sheng Li wrote:
> I don't get it. What's the issue you tried to fix with that?

There is no separate v2ctl executable file in v5.

I let it judge whether this file exists so that this content will not be displayed when installing v5:

```
# bash install-release.sh
installed: /usr/local/bin/v2ctl
```

```
# bash install-release.sh --remove
rm: cannot remove '/usr/local/bin/v2ctl': No such file or directory
```

-- 
Dct Mei

-----BEGIN PGP PUBLIC KEY BLOCK-----

mDMEXCinkBYJKwYBBAHaRw8BAQdA5H9IxywOaNmJIWhPWmOW373e5qV9B2XX4uaN
8Dj/os60HERjdCBNZWkgPGRjdHhtZWlAeWFuZGV4LmNvbT6IkAQTFggAOAIbAwUL
CQgHAgYVCgkICwIEFgIDAQIeAQIXgBYhBHsxS+d9vKIOAt27wFC/i3EtytfqBQJg
F24ZAAoJEFC/i3EtytfqTcUA/2n/BRU+vrnhphWMwXLpFG6BNxnm3cKrlVrlGkdz
+Ww2AQDbbodVwahMIIJNZ+Hu2EaOY5yskrGzjlnHuW4qO7eLDLQbRGN0IE1laSA8
ZGN0eG1laUBnbWFpbC5jb20+iHcEMBYIACAWIQR7MUvnfbyiDgLdu8BQv4txLcrX
6gUCYBduMAIdIAAKCRBQv4txLcrX6vHoAQCv5IeimcILSpwX96JpMuigMySY0gNb
71vTQMYjckTRuQD3fd20co+cHvLK5r2QI7MoGc/xHoPudlufl0vv7etfC7g4BFwo
p5ASCisGAQQBl1UBBQEBB0Axr/Hhs7IfrRZIfGH4m6eDLb/eAMMjeOcdQILs1FVH
IwMBCAeIeAQYFggAIBYhBHsxS+d9vKIOAt27wFC/i3EtytfqBQJcKKeQAhsMAAoJ
EFC/i3EtytfqR4IBANEM6wOjfu9kinIYp5pmh9bwZPM3IPBBn8U0zIL7bUUFAQC/
kqhy8LoX1Th4EIugjgvkkCOY60QGIY6yaHPih7xzCA==
=kO/D
-----END PGP PUBLIC KEY BLOCK-----

**Comment by digglife** [comment]
@dctxmei Got it. I didn't notice that v2ctl is gone. Thanks!

**Comment by kslr** [comment]
Sorry, I've been a bit down lately and haven't been following github.

**Comment by digglife** [comment]
> Sorry, I've been a bit down lately and haven't been following github.

No problem. Thanks for your time. Hope you feel better soon!

**Pull request merged**
